SELECT * FROM CUSTOMER;
--Q1. What is the total revenue generated by male vs. female customers?
SELECT GENDER , SUM(PURCHASE_AMOUNT)AS REVENUE
FROM CUSTOMER
GROUP BY GENDER;
--male customers generate more revenue as compared to female customers. This will hlp businss design better targeted campaign
--for each group.


--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT CUSTOMER_ID, PURCHASE_AMOUNT FROM CUSTOMER
WHERE DISCOUNT_APPLIED = 'Yes' AND PURCHASE_AMOUNT > (SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMER )

--Q3. Which are the top 5 products with the highest average review rating?
SELECT ITEM_PURCHASED , AVG(REVIEW_RATING) AS "AVERAGE PRODUCT RATING"
FROM CUSTOMER 
GROUP BY ITEM_PURCHASED
ORDER BY AVG(REVIEW_RATING) DESC
LIMIT 5;
-- Products with consistent highest rating can be highlighted in the marketing campaigns to increase the revenue and can be sold at
--premium pricing.


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT SHIPPING_TYPE , AVG(PURCHASE_AMOUNT) FROM CUSTOMER 
WHERE SHIPPING_TYPE IN ('Standard','Express')
GROUP BY  SHIPPING_TYPE
--Business should focus  more in express shipping or otherfaster delivery options according to the results.


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT SUBSCRIPTION_STATUS , COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS,
AVG(PURCHASE_AMOUNT) AS AVG_SPEND,
SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY SUBSCRIPTION_STATUS  ORDER BY TOTAL_REVENUE, AVG_SPEND DESC;
--Suscription offrs are not working properly according to the results as the total revenue generated by non subscribers are very 
--much higher. So, business should focus on making attractive offers for the subscriberws to gain more subscriptions.


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT ITEM_PURCHASED ,(100 *  SUM(CASE WHEN DISCOUNT_APPLIED = 'Yes' THEN 1 ELSE 0 END)/COUNT(*)) AS DISCOUNT_RATE
FROM CUSTOMER 
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC LIMIT 5;
--Ths products rely heavily on discounts for sales.


--Q7. Segment customers into New, Returning, and Loyal based on their total number ofprevious purchases, and show the count of each segment.
WITH CUSTOMER_TYPE AS (
SELECT CUSTOMER_ID, PREVIOUS_PURCHASES,
CASE
	WHEN PREVIOUS_PURCHASES = 1 THEN 'New'
    WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10  THEN 'Returning'
	ELSE 'loyal'
	END AS CUSTOMER_SEGMENT
FROM CUSTOMER
)
SELECT CUSTOMER_SEGMENT , COUNT(*) AS NUMBER_OF_CUSTOMER
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT
--Number of loyal customers are more , so business is doing good in returning customers.


--Q8. What are the top 3 most purchased products within each category?
WITH ITEM_COUNTS AS(
SELECT CATEGORY,ITEM_PURCHASED,COUNT(CUSTOMER_ID) AS TOTAL_ORDERS,
ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY COUNT(CUSTOMER_ID)DESC ) AS ITEM_RANK 
from customer
group by category, item_purchased
)
SELECT ITEM_RANK , CATEGORY , ITEM_PURCHASED , TOTAL_ORDERS
FROM ITEM_COUNTS
WHERE ITEM_RANK<=3;
--This will help business which products are working good in each category and will focus more on increasing revenue for 
--particular products .


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT SUBSCRIPTION_STATUS , COUNT(CUSTOMER_ID) AS REPEAT_BUYERS
FROM CUSTOMER
WHERE PREVIOUS_PURCHASES > 5
GROUP BY SUBSCRIPTION_STATUS;
-- more no. of loyal customers i.e the repeat buyers are not subscribing , it means subscription offers aren't attractive enough.


--Q10. What is the revenue contribution of each age group?
SELECT AGE_GROUP, SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY AGE_GROUP
ORDER BY TOTAL_REVENUE DESC;
-- young adult drives the most revenue . They are the most valueable customer to the business.